### ISSUE TITLE
Add SSL

### ISSUE THREAD

**Issue by FrancescoSTL** [mozilla/all-aboard-remote#3]
Once we've finished updating index.html, we can ping @lonnen and he will add SSL to the heroku app.

**Comment by chrismore** [comment]
We have SSL now.

![screen shot 2016-07-06 at 10 11 01 am](https://cloud.githubusercontent.com/assets/751491/16627412/00e81db2-4362-11e6-8658-e3834ffbcb33.png)

**Comment by lonnen** [comment]
That should be the built in SSL that comes with herokuapp. Nothing special to do there. If you want a vanity domain, or a cname that you can use to redirect this in the future we'll need to do some extra setup. Worth thinking about now, the hardcoded url tends to be hard to change once it is out the door.
